# Model Training

## Objective

The objective of this notebook is to train multiple machine learning models using the preprocessed dataset.
These models will later be evaluated to determine which performs best for credit card fraud detection.

In [30]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [31]:
df = pd.read_csv("../data/processed/processed_creditcard.csv")

df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.996823,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244200,0
1,-1.996823,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342584,0
2,-1.996802,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.158900,0
3,-1.996802,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.139886,0
4,-1.996781,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073813,0

Preparing features and targate

In [32]:
X = df.drop("Class", axis=1)

Y = df["Class"]

In [33]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.996823,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244200
1,-1.996823,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342584
2,-1.996802,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.158900
3,-1.996802,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.139886
4,-1.996781,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073813

In [34]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

### Observation
The input features and target variable were successfully separated.

# Splitting Testing and Training data

In [35]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [36]:
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", Y_train.shape)
print("Testing Labels:", Y_test.shape)

Training Features: (226980, 30)
Testing Features: (56746, 30)
Training Labels: (226980,)
Testing Labels: (56746,)

### Observation
The dataset was divided into training and testing datasets using an 80:20 ratio.

# Training Logic Regression

In [37]:
logistic_model = LogisticRegression(
    random_state=42,
    max_iter=1000,
    class_weight="balanced"
)

logistic_model.fit(X_train, Y_train)

print("Logistic Regression trained successfully.")

Logistic Regression trained successfully.

# Training Decision Tree

In [38]:
decision_tree = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced"
)

decision_tree.fit(X_train, Y_train)

print("Decision Tree trained successfully.")

Decision Tree trained successfully.

# Training Random Forest

In [39]:
random_forest = RandomForestClassifier(
    random_state=42,
    n_estimators=100,
    class_weight="balanced"
)

random_forest.fit(X_train, Y_train)

print("Random Forest trained successfully.")

Random Forest trained successfully.

# Training Gradient Boosting

In [40]:
gradient_boost = GradientBoostingClassifier(
    random_state=42
)

gradient_boost.fit(X_train, Y_train)

print("Gradient Boosting trained successfully.")

Gradient Boosting trained successfully.

## Saving Tree Models

In [43]:
joblib.dump(logistic_model, "../models/logistic_regression.pkl")

joblib.dump(decision_tree, "../models/decision_tree.pkl")

joblib.dump(random_forest, "../models/random_forest.pkl")

joblib.dump(gradient_boost, "../models/gradient_boosting.pkl")

['../models/gradient_boosting.pkl']

In [44]:
import os

os.listdir("../models")

['.gitkeep',
 'decision_tree.pkl',
 'gradient_boosting.pkl',
 'logistic_regression.pkl',
 'random_forest.pkl']

## Observation
All trained machine learning models were successfully saved in the models directory.

# Final Summary
- The processed dataset was successfully loaded.
- Features and target variable were separated.
- The dataset was split into training and testing sets.
- Four machine learning models were trained:
  - Logistic Regression
  - Decision Tree
  - Random Forest
  - Gradient Boosting
- All trained models were saved for evaluation.
- The project is now ready for model evaluation.